apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: token-exchange-agent-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
