apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: odfmo-controller-manager
  name: odfmo-webhook-service
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: odfmo-controller-manager
status:
  loadBalancer: {}
