
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-multicluster-odf-openshift-io-v1alpha1-mirrorpeer
  failurePolicy: Fail
  name: mmirrorpeer.kb.io
  rules:
  - apiGroups:
    - multicluster.odf.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mirrorpeers
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-multicluster-odf-openshift-io-v1alpha1-mirrorpeer
  failurePolicy: Fail
  name: vmirrorpeer.kb.io
  rules:
  - apiGroups:
    - multicluster.odf.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - mirrorpeers
  sideEffects: None
