# permissions for end users to edit mirrorpeers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirrorpeer-editor-role
rules:
- apiGroups:
  - multicluster.odf.openshift.io
  resources:
  - mirrorpeers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multicluster.odf.openshift.io
  resources:
  - mirrorpeers/status
  verbs:
  - get
