name: Build images

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build orchestrator image
      run: make docker-build