name: Run integration tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  integration-test:
    name: integration-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run integration tests
      run: make test