name: Tests & Builds

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  GO_VERSION: "1.16"

defaults:
  run:
    shell: bash

jobs:
  clean-workdir:
    name: Ensure Clean Workdir
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Scan for uncommitted changes
      run: make ensure-clean-workdir

  unit-test:
    name: Unit Tests
    needs: clean-workdir
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run unit tests
      run: make unit-test

  integration-test:
    name: Integration Tests
    needs: clean-workdir
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run integration tests
      run: make test

  build-operator:
    name: Build Operator Image
    needs: [unit-test,integration-test]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build
      run: make docker-build

  validate-bundle:
    name: Validate Operator Bundle
    needs: clean-workdir
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Validate
      run: make bundle

  build-bundle:
    name: Build Bundle Image
    needs: validate-bundle
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build
      run: make bundle-build